from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import numpy as np

from .audio_tools import dominant_key, export_audio_clip, grid_rhythm, note_sequence_from_pitch_track


@dataclass
class StrudelResult:
    tempo: float
    root: str
    notes: List[str]
    rhythm: List[str]
    preview_path: Optional[Path]

    def to_code(self) -> str:
        tempo_line = f"tempo {int(round(self.tempo)) if self.tempo > 0 else 120}"
        note_pattern = " ".join(self.notes) if self.notes else "c3 ~ g3 ~"
        rhythm_pattern = " ".join(self.rhythm) if self.rhythm else "bd ~ bd ~"

        lines = [
            "-- Generated by Strudel Converter",
            tempo_line,
            "stack [",
            f"  n \"{note_pattern}\"",
            "  # legato 0.9",
            "  # shape 0.3",
            f", sound \"{rhythm_pattern}\"",
            "  # gain 1.1",
            "]",
            f"# root {self.root}",
        ]

        if self.preview_path:
            lines.append(f"-- preview saved at {self.preview_path}")

        return "\n".join(lines)


def build_strudel_result(
    tempo: float,
    chroma: np.ndarray,
    pitches: np.ndarray,
    sr: int,
    onset_times: np.ndarray,
    audio: np.ndarray,
) -> StrudelResult:
    root = dominant_key(chroma)
    notes = note_sequence_from_pitch_track(pitches, sr=sr, onset_times=onset_times)

    if notes:
        # emphasize repeating motifs for musicality
        counts = {}
        for n in notes:
            counts[n] = counts.get(n, 0) + 1
        sorted_notes = sorted(notes, key=lambda x: counts.get(x, 0), reverse=True)
        notes = sorted_notes[:8]

    rhythm = grid_rhythm(onset_times, tempo=tempo)
    preview = export_audio_clip(audio, sr=sr) if audio.size else None

    return StrudelResult(
        tempo=tempo,
        root=root,
        notes=notes,
        rhythm=rhythm,
        preview_path=preview,
    )
